apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: p8sa
spec:
  selector:
    app: backend
  ports:
    - name: backend-port
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: 35.194.31.162
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: p8sa
spec:
  selector:
    app: frontend
  ports:
    - name: frontend-port
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 35.232.124.147
