---
- hosts: servers
  become: true

  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: log into docker hub registry
      docker_login:
        username: "201800726"
        password: "{{DOKERHUB_PWD}}"
    - name: ensure a container is running
      docker_container:
        name: practice5
        state: started
        image: "201800726/pareja3:latest"
        pull: true
        ports:
          - "80:80"