pipeline {
  agent any
  environment {
    VITE_STUDENT1ID = credentials('id-s1')
    VITE_STUDENT1NICKNAME = credentials('nickname-s1')
    VITE_STUDENT1NAME = credentials('name-s1')
    VITE_STUDENT1IMG = credentials('img-s1')

    VITE_STUDENT2ID= credentials('id-s2')
    VITE_STUDENT2NICKNAME= credentials('nickname-s2')
    VITE_STUDENT2NAME= credentials('name-s2')
    VITE_STUDENT2IMG= credentials('img-s2')

    GCR_ID = credentials('PROJECT_ID')
    // Credenciales (.json) con los permisos de: 'Administrador de Acceso a VPC sin servidores', 'Administrador de Compute', 'Agente de servicios de recursos de nube', 'Visualizador de objetos de Storage'
    GOOGLE_APPLICATION_CREDENTIALS = credentials('GOOGLE_APPLICATION_CREDENTIALS')
  }

  parameters {
    string(name: 'container_name', defaultValue: 'practica8', description: 'Nombre del contenedor')
    string(name: 'image_name', defaultValue: 'pareja3', description: 'Nombre de la imagen')
    string(name: 'image_tag', defaultValue: 'latest', description: 'Etiqueta de la imagen')
    string(name: 'container_port', defaultValue: '80', description: 'Puerto a publicar')
  }

  stages {
    stage('Set Credentials') {
      steps {
        sh 'cat ${GOOGLE_APPLICATION_CREDENTIALS} | docker login -u _json_key --password-stdin https://gcr.io'
      }
    }

    stage('Test') {
      steps {
        script{
          sh '''
            cd Practica_8
            npm install
            npm run test
          '''
        }
      }
    }

    stage('Build') {
      steps {
        script{
          sh '''
            cd Practica_7
            docker build \
              --build-arg VITE_STUDENT1ID=${VITE_STUDENT1ID} \
              --build-arg VITE_STUDENT1NICKNAME=${VITE_STUDENT1NICKNAME} \
              --build-arg VITE_STUDENT1NAME="${VITE_STUDENT1NAME}" \
              --build-arg VITE_STUDENT1IMG=${VITE_STUDENT1IMG} \
              --build-arg VITE_STUDENT2ID=${VITE_STUDENT2ID} \
              --build-arg VITE_STUDENT2NICKNAME=${VITE_STUDENT2NICKNAME} \
              --build-arg VITE_STUDENT2NAME="${VITE_STUDENT2NAME}" \
              --build-arg VITE_STUDENT2IMG=${VITE_STUDENT2IMG} \
              -t ${GCR_ID}/${image_name}:${image_tag} .

            docker push ${GCR_ID}/${image_name}:${image_tag}
          '''
        }
      }
    }

    stage('Deploy') {
      steps {
        script{
          sh '''
            export GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
            cd Practica_8
          '''
        }
      }
    }
  }
}
